<?php

/**
 * This is the model base class for the table "classic_follow_user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FollowUser".
 *
 * Columns in table "classic_follow_user" available as properties of the model,
 * followed by relations of table "classic_follow_user" available as properties of the model.
 *
 * @property string $user_id
 * @property string $follow_user_id
 * @property string $create_time
 *
 * @property User $user
 * @property User $followUser
 */
abstract class BaseFollowUser extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'classic_follow_user';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FollowUser|FollowUsers', $n);
	}

	public static function representingColumn() {
		return 'create_at';
	}

	public function rules() {
		return array(
			array('user_id, follow_user_id', 'length', 'max'=>10),
			array('create_at', 'safe'),
			array('user_id, follow_user_id, create_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('user_id, follow_user_id, create_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
			'followUser' => array(self::BELONGS_TO, 'User', 'follow_user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'user_id' => null,
			'follow_user_id' => null,
			'create_at' => Yii::t('app', 'Create Time'),
			'user' => null,
			'followUser' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('follow_user_id', $this->follow_user_id);
		$criteria->compare('create_at', $this->create_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}