<?php

/**
 * This is the model base class for the table "classic_follow_course".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FollowCourse".
 *
 * Columns in table "classic_follow_course" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $user_id
 * @property string $course_id
 * @property string $follow_type
 * @property string $create_time
 *
 */
abstract class BaseFollowCourse extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'classic_follow_course';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FollowCourse|FollowCourses', $n);
	}

	public static function representingColumn() {
		return array(
			'user_id',
			'course_id',
		);
	}

	public function rules() {
		return array(
			array('user_id, course_id', 'required'),
			array('user_id, course_id, follow_type', 'length', 'max'=>10),
			array('follow_type', 'default', 'setOnEmpty' => true, 'value' => null),
			array('user_id, course_id, follow_type, create_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'user_id' => null,
			'course_id' => null,
			'follow_type' => Yii::t('app', 'Follow Type'),
			'create_at' => Yii::t('app', 'Create Time'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('course_id', $this->course_id);
		$criteria->compare('follow_type', $this->follow_type, true);
		$criteria->compare('create_at', $this->create_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}