<?php

/**
 * This is the model base class for the table "classic_department".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Department".
 *
 * Columns in table "classic_department" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $raw_id
 * @property string $name
 *
 * The followings are the available model relations:
 * @property Major[] $majors
 */
abstract class BaseDepartment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'classic_department';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Department|Departments', $n);
	}

	public static function representingColumn() {
		return 'raw_id';
	}

	public function rules() {
		return array(
			array('raw_id, name', 'required'),
			array('raw_id', 'length', 'max'=>10),
			array('name', 'length', 'max'=>255),
			array('id, raw_id, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
        return array(
            'majors' => array(self::HAS_MANY, 'Major', 'dep_id'),
        );
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'raw_id' => Yii::t('app', 'Raw'),
			'name' => Yii::t('app', 'Name'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('raw_id', $this->raw_id, true);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}