<?php

/**
 * This is the model base class for the table "classic_teaching".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Teaching".
 *
 * Columns in table "classic_teaching" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $teacher_id
 * @property string $class_id
 *
 */
abstract class BaseTeaching extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'classic_teaching';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Teaching|Teachings', $n);
	}

	public static function representingColumn() {
		return array(
			'teacher_id',
			'class_id',
		);
	}

	public function rules() {
		return array(
			array('teacher_id, class_id', 'required'),
			array('teacher_id, class_id', 'length', 'max'=>10),
			array('teacher_id, class_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'teacher_id' => null,
			'class_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('teacher_id', $this->teacher_id);
		$criteria->compare('class_id', $this->class_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}