<?php

/**
 * This is the model base class for the table "classic_teacher".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Teacher".
 *
 * Columns in table "classic_teacher" available as properties of the model,
 * followed by relations of table "classic_teacher" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $gender
 * @property string $introduction
 *
 * * The followings are the available model relations:
 * @property CourseDocument[] $courseDocuments
 * @property CourseResource[] $courseResources
 * @property CourseBook[] $courseBooks
 * @property ActualClass[] $classes
 */
abstract class BaseTeacher extends GxActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'classic_teacher';
    }

    public static function label($n = 1)
    {
        return Yii::t('app', 'Teacher|Teachers', $n);
    }

    public static function representingColumn()
    {
        return 'name';
    }

    public function rules()
    {
        return array(
            array('name', 'required'),
            array('name', 'length', 'max' => 32),
            array('gender', 'length', 'max' => 6),
            array('introduction', 'filter', 'filter' => array(Common::getHtmlPurifier(), 'purify')),
            array('gender, introduction', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, name, gender, introduction', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
            'courseDocuments' => array(self::HAS_MANY, 'CourseDocument', 'teacher_id'),
            'courseResources' => array(self::HAS_MANY, 'CourseResource', 'teacher_id'),
            'courseBooks' => array(self::HAS_MANY, 'CourseBook', 'teacher_id'),
            'classes' => array(self::MANY_MANY, 'ActualClass', Teaching::model()->tableName() . '(teacher_id, class_id)'),);
    }

    public function pivotModels()
    {
        return array(
            'classes' => 'Teaching',
        );
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'gender' => Yii::t('app', 'Gender'),
            'introduction' => Yii::t('app', 'Introduction'),
            'classes' => null,
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id, true);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('gender', $this->gender, true);
        $criteria->compare('introduction', $this->introduction, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}