<?php

/**
 * This is the model base class for the table "classic_major".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Major".
 *
 * Columns in table "classic_major" available as properties of the model,
 * followed by relations of table "classic_major" available as properties of the model.
 *
 * @property string $id
 * @property string $raw_id
 * @property string $dep_id
 * @property string $name
 *
 * The followings are the available model relations:
 * @property ActualClass[] $classes
 * @property Department $dep
 */
abstract class BaseMajor extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'classic_major';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Major|Majors', $n);
	}

	public static function representingColumn() {
		return 'raw_id';
	}

	public function rules() {
		return array(
			array('raw_id, dep_id, name', 'required'),
			array('raw_id, dep_id', 'length', 'max'=>10),
			array('name', 'length', 'max'=>45),
			array('id, raw_id, dep_id, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
            'classes' => array(self::HAS_MANY, 'ActualClass', 'major_id'),

            'dep' => array(self::BELONGS_TO, 'Department', 'dep_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'raw_id' => Yii::t('app', 'Raw'),
			'dep_id' => null,
			'name' => Yii::t('app', 'Name'),
			'dep' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('raw_id', $this->raw_id, true);
		$criteria->compare('dep_id', $this->dep_id);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}