<?php

/**
 * This is the model base class for the table "global_user_operation_key".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserOperationKey".
 *
 * Columns in table "global_user_operation_key" available as properties of the model,
 * followed by relations of table "global_user_operation_key" available as properties of the model.
 *
 * @property string $user_id
 * @property string $operation
 * @property string $key
 * @property string $create_at
 *
 * @property User $user
 */
abstract class BaseUserOperationKey extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'global_user_operation_key';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserOperationKey|UserOperationKeys', $n);
	}

	public static function representingColumn() {
		return 'key';
	}

	public function rules() {
		return array(
			array('user_id, operation, key', 'required'),
			array('user_id', 'length', 'max'=>11),
			array('operation', 'length', 'max'=>40),
			array('key', 'length', 'max'=>60),
			array('create_at', 'safe'),
			array('create_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('user_id, operation, key, create_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'user_id' => null,
			'operation' => Yii::t('app', 'Operation'),
			'key' => Yii::t('app', 'Key'),
			'create_at' => Yii::t('app', 'Create At'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('operation', $this->operation, true);
		$criteria->compare('key', $this->key, true);
		$criteria->compare('create_at', $this->create_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}