<?php

/**
 * This is the model base class for the table "service_email".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ServiceEmail".
 *
 * Columns in table "service_email" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $has_been_sent
 * @property string $category
 * @property string $create_time
 * @property string $send_time
 * @property string $to
 * @property string $from
 * @property string $subject
 * @property string $body
 *
 */
abstract class BaseServiceEmail extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'service_email';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ServiceEmail|ServiceEmails', $n);
	}

	public static function representingColumn() {
		return 'has_been_sent';
	}

	public function rules() {
		return array(
			array('create_at, to, from, subject, body', 'required'),
			array('has_been_sent', 'length', 'max'=>3),
			array('category', 'length', 'max'=>5),
			array('to, from, subject', 'length', 'max'=>255),
			array('send_time', 'safe'),
			array('has_been_sent, category, send_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, has_been_sent, category, create_at, send_time, to, from, subject, body', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'has_been_sent' => Yii::t('app', 'Has Been Sent'),
			'category' => Yii::t('app', 'Category'),
			'create_at' => Yii::t('app', 'Create Time'),
			'send_time' => Yii::t('app', 'Send Time'),
			'to' => Yii::t('app', 'To'),
			'from' => Yii::t('app', 'From'),
			'subject' => Yii::t('app', 'Subject'),
			'body' => Yii::t('app', 'Body'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('has_been_sent', $this->has_been_sent, true);
		$criteria->compare('category', $this->category, true);
		$criteria->compare('create_at', $this->create_at, true);
		$criteria->compare('send_time', $this->send_time, true);
		$criteria->compare('to', $this->to, true);
		$criteria->compare('from', $this->from, true);
		$criteria->compare('subject', $this->subject, true);
		$criteria->compare('body', $this->body, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}